// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AppSettingRead
 */
export type AppSettingRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Value
     */
    value: {
        [key: string]: unknown;
    } | Array<unknown> | string | number | number | boolean | null;
};

/**
 * AppSettings
 *
 * Central definition of application-level configuration.
 *
 * Each field in this model represents a single configurable setting and
 * maps to one record in the `AppSetting` database table.
 *
 * Defaults defined here are used as fallbacks and as initial values during
 * database synchronization.
 *
 * After adding, removing, or modifying fields in this model, run:
 *
 * python -m cli db sync
 *
 * to synchronize the definitions with the database.
 *
 * Notes:
 * - The setting name is derived from the field name by default.
 * - A custom name can be provided via `Field(name=...)`.
 * - Optional metadata such as descriptions should also be defined via `Field`.
 */
export type AppSettingsInput = {
    /**
     * Fiat Commission
     */
    fiat_commission?: number | string;
    /**
     * Crypto Commission
     */
    crypto_commission?: number | string;
};

/**
 * AppSettings
 *
 * Central definition of application-level configuration.
 *
 * Each field in this model represents a single configurable setting and
 * maps to one record in the `AppSetting` database table.
 *
 * Defaults defined here are used as fallbacks and as initial values during
 * database synchronization.
 *
 * After adding, removing, or modifying fields in this model, run:
 *
 * python -m cli db sync
 *
 * to synchronize the definitions with the database.
 *
 * Notes:
 * - The setting name is derived from the field name by default.
 * - A custom name can be provided via `Field(name=...)`.
 * - Optional metadata such as descriptions should also be defined via `Field`.
 */
export type AppSettingsOutput = {
    /**
     * Fiat Commission
     */
    fiat_commission?: string;
    /**
     * Crypto Commission
     */
    crypto_commission?: string;
};

/**
 * BlockchainRead
 */
export type BlockchainRead = {
    /**
     * Name
     */
    name: string;
};

/**
 * Body_create_kyc_document
 */
export type BodyCreateKycDocument = {
    /**
     * Doc Type Id
     */
    doc_type_id: string;
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * Body_create_payment
 */
export type BodyCreatePayment = {
    /**
     * Receipt
     */
    receipt?: Blob | File | null;
};

/**
 * Body_create_ticket
 */
export type BodyCreateTicket = {
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string | null;
    /**
     * Files
     */
    files?: Array<Blob | File>;
};

/**
 * Body_create_ticket_message
 */
export type BodyCreateTicketMessage = {
    /**
     * Message
     */
    message: string | null;
    /**
     * Files
     */
    files?: Array<Blob | File> | null;
};

/**
 * Body_login_access_token
 */
export type BodyLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CurrencyRead
 */
export type CurrencyRead = {
    /**
     * Id
     */
    id: string;
    type: CurrencyType;
    /**
     * Name
     */
    name: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Sign
     */
    sign: string | null;
    /**
     * Decimals
     */
    decimals: number;
    /**
     * Logo
     */
    logo: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Token Std
     */
    token_std: string | null;
    blockchain: BlockchainRead | null;
    /**
     * Contract Address
     */
    contract_address: string | null;
    /**
     * Logo Url
     */
    readonly logo_url: string;
};

/**
 * CurrencyType
 */
export type CurrencyType = 'fiat' | 'crypto';

/**
 * FileRead
 */
export type FileRead = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Filename
     */
    filename: string | null;
    /**
     * Extension
     */
    extension: string | null;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * Size
     */
    size: number | null;
};

/**
 * FileSetRead
 */
export type FileSetRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Files
     */
    files: Array<FileRead>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InvoiceCreate
 */
export type InvoiceCreateInput = {
    /**
     * Amount
     */
    amount: number | string;
    /**
     * Currency
     */
    currency: string;
    type: InvoiceType;
};

/**
 * InvoiceCreate
 */
export type InvoiceCreateOutput = {
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    type: InvoiceType;
};

/**
 * InvoiceRead
 */
export type InvoiceRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    type: InvoiceType;
    /**
     * Created At
     */
    created_at: string;
    status: InvoiceStatus;
    /**
     * Expires At
     */
    expires_at: string | null;
};

/**
 * InvoiceStatus
 *
 * Enum for the status of an invoice.
 */
export type InvoiceStatus = 'paid' | 'unpaid' | 'expired' | 'cancelled';

/**
 * InvoiceType
 */
export type InvoiceType = 'wallet_top_up' | 'offer_commission';

/**
 * InvoicesRead
 */
export type InvoicesRead = {
    /**
     * Data
     */
    data: Array<InvoiceRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * KycDocumentRead
 */
export type KycDocumentRead = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    type: KycDocumentTypeRead;
    file_set: FileSetRead;
    status: KycDocumentStatus;
    /**
     * Expires At
     */
    expires_at: string | null;
};

/**
 * KycDocumentReviewCreate
 */
export type KycDocumentReviewCreate = {
    action: KycReviewAction;
    /**
     * Rejection Reason
     */
    rejection_reason: string | null;
};

/**
 * KycDocumentStatus
 */
export type KycDocumentStatus = 'pending_review' | 'approved' | 'rejected' | 'expired';

/**
 * KycDocumentTypeCreate
 */
export type KycDocumentTypeCreate = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * KycDocumentTypeRead
 */
export type KycDocumentTypeRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * KycReviewAction
 */
export type KycReviewAction = 'approve' | 'reject' | 'request_more_info' | 'expire';

/**
 * Maker
 */
export type Maker = {
    profile: ProfilePublic;
    /**
     * Username
     */
    username: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OfferCreate
 */
export type OfferCreate = {
    /**
     * Sell Asset Id
     */
    sell_asset_id: string;
    /**
     * Buy Asset Id
     */
    buy_asset_id: string;
    /**
     * Price
     */
    price: number | string;
    /**
     * Total Amount
     */
    total_amount: number | string;
    /**
     * Min Lock Amount
     */
    min_lock_amount?: number | string | null;
    /**
     * Max Lock Amount
     */
    max_lock_amount?: number | string | null;
    /**
     * Expires At
     */
    expires_at: string | null;
};

/**
 * OfferLockCreate
 */
export type OfferLockCreate = {
    /**
     * Locked Amount
     */
    locked_amount: number | string;
};

/**
 * OfferLockRead
 */
export type OfferLockRead = {
    /**
     * Id
     */
    id: string;
};

/**
 * OfferPublic
 */
export type OfferPublic = {
    /**
     * Id
     */
    id: string;
    maker: Maker;
    sell: CurrencyRead;
    buy: CurrencyRead;
    /**
     * Price
     */
    readonly price: string;
    /**
     * Total Amount
     */
    readonly total_amount: string;
    /**
     * Min Lock Amount
     */
    readonly min_lock_amount: string;
    /**
     * Available Amount
     */
    readonly available_amount: string;
};

/**
 * OffersPublic
 */
export type OffersPublic = {
    /**
     * Data
     */
    data: Array<OfferPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Page[KycDocumentRead]
 */
export type PageKycDocumentRead = {
    /**
     * Items
     */
    items: Array<KycDocumentRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PaymentMethodEnum
 */
export type PaymentMethodEnum = 'crypto' | 'paypal' | 'wallet' | 'bank_transfer';

/**
 * PaymentRead
 */
export type PaymentRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Invoice Id
     */
    invoice_id: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    status: PaymentStatus;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PaymentStatus
 *
 * Enum for the status of a payment.
 */
export type PaymentStatus = 'pending' | 'success' | 'failed';

/**
 * PaymentsRead
 */
export type PaymentsRead = {
    /**
     * Data
     */
    data: Array<PaymentRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * ProfilePublic
 */
export type ProfilePublic = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar
     */
    avatar?: string | null;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Avatar Url
     */
    readonly avatar_url: string;
};

/**
 * TicketMessageRead
 */
export type TicketMessageRead = {
    /**
     * Id
     */
    id: string;
    sender: TicketSender;
    /**
     * Message
     */
    message: string | null;
    file_set: FileSetRead | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TicketMessagesRead
 */
export type TicketMessagesRead = {
    /**
     * Data
     */
    data: Array<TicketMessageRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * TicketRead
 */
export type TicketRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Subject
     */
    subject: string;
    status: TicketStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TicketSender
 */
export type TicketSender = {
    /**
     * Username
     */
    username: string;
};

/**
 * TicketStatus
 */
export type TicketStatus = 'open' | 'closed';

/**
 * TicketUpdate
 */
export type TicketUpdate = {
    status: TicketStatus;
};

/**
 * TicketsRead
 */
export type TicketsRead = {
    /**
     * Data
     */
    data: Array<TicketRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
};

/**
 * UserMe
 */
export type UserMe = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    profile?: ProfilePublic | null;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * CurrencyRead
 */
export type CurrencyReadWritable = {
    /**
     * Id
     */
    id: string;
    type: CurrencyType;
    /**
     * Name
     */
    name: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Sign
     */
    sign: string | null;
    /**
     * Decimals
     */
    decimals: number;
    /**
     * Logo
     */
    logo: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Token Std
     */
    token_std: string | null;
    blockchain: BlockchainRead | null;
    /**
     * Contract Address
     */
    contract_address: string | null;
};

/**
 * Maker
 */
export type MakerWritable = {
    profile: ProfilePublicWritable;
    /**
     * Username
     */
    username: string;
};

/**
 * OfferPublic
 */
export type OfferPublicWritable = {
    /**
     * Id
     */
    id: string;
    maker: MakerWritable;
    sell: CurrencyReadWritable;
    buy: CurrencyReadWritable;
};

/**
 * OffersPublic
 */
export type OffersPublicWritable = {
    /**
     * Data
     */
    data: Array<OfferPublicWritable>;
    /**
     * Count
     */
    count: number;
};

/**
 * ProfilePublic
 */
export type ProfilePublicWritable = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar
     */
    avatar?: string | null;
};

/**
 * UserMe
 */
export type UserMeWritable = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    profile?: ProfilePublicWritable | null;
};

export type LoginAccessTokenData = {
    body: BodyLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenError = LoginAccessTokenErrors[keyof LoginAccessTokenErrors];

export type LoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenResponse = LoginAccessTokenResponses[keyof LoginAccessTokenResponses];

export type TestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type TestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type TestTokenResponse = TestTokenResponses[keyof TestTokenResponses];

export type RecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type RecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordError = RecoverPasswordErrors[keyof RecoverPasswordErrors];

export type RecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RecoverPasswordResponse = RecoverPasswordResponses[keyof RecoverPasswordResponses];

export type ResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type ResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type RecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type RecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordHtmlContentError = RecoverPasswordHtmlContentErrors[keyof RecoverPasswordHtmlContentErrors];

export type RecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type RecoverPasswordHtmlContentResponse = RecoverPasswordHtmlContentResponses[keyof RecoverPasswordHtmlContentResponses];

export type ReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type ReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersError = ReadUsersErrors[keyof ReadUsersErrors];

export type ReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type ReadUsersResponse = ReadUsersResponses[keyof ReadUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type DeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserMeResponse = DeleteUserMeResponses[keyof DeleteUserMeResponses];

export type ReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserMe;
};

export type ReadUserMeResponse = ReadUserMeResponses[keyof ReadUserMeResponses];

export type UpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeError = UpdateUserMeErrors[keyof UpdateUserMeErrors];

export type UpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserMe;
};

export type UpdateUserMeResponse = UpdateUserMeResponses[keyof UpdateUserMeResponses];

export type UpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordMeError = UpdatePasswordMeErrors[keyof UpdatePasswordMeErrors];

export type UpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UpdatePasswordMeResponse = UpdatePasswordMeResponses[keyof UpdatePasswordMeResponses];

export type RegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdError = ReadUserByIdErrors[keyof ReadUserByIdErrors];

export type ReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByIdResponse = ReadUserByIdResponses[keyof ReadUserByIdResponses];

export type UpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ReadSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/';
};

export type ReadSettingsResponses = {
    /**
     * Response Read Settings
     *
     * Successful Response
     */
    200: Array<AppSettingRead>;
};

export type ReadSettingsResponse = ReadSettingsResponses[keyof ReadSettingsResponses];

export type UpdateSettingsData = {
    body: AppSettingsInput;
    path?: never;
    query?: never;
    url: '/api/v1/settings/';
};

export type UpdateSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    /**
     * Successful Response
     */
    200: AppSettingsOutput;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type TestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type TestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestEmailError = TestEmailErrors[keyof TestEmailErrors];

export type TestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type TestEmailResponse = TestEmailResponses[keyof TestEmailResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type HealthCheckResponses = {
    /**
     * Response Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type ReadOffersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/offers/';
};

export type ReadOffersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadOffersError = ReadOffersErrors[keyof ReadOffersErrors];

export type ReadOffersResponses = {
    /**
     * Successful Response
     */
    200: OffersPublic;
};

export type ReadOffersResponse = ReadOffersResponses[keyof ReadOffersResponses];

export type CreateOfferData = {
    body: OfferCreate;
    path?: never;
    query?: never;
    url: '/api/v1/offers/';
};

export type CreateOfferErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOfferError = CreateOfferErrors[keyof CreateOfferErrors];

export type CreateOfferResponses = {
    /**
     * Successful Response
     */
    200: OfferPublic;
};

export type CreateOfferResponse = CreateOfferResponses[keyof CreateOfferResponses];

export type SearchOffersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Type
         */
        type: 'buy' | 'sell';
        /**
         * Target
         */
        target: string;
        /**
         * Amount
         */
        amount: number | string;
        /**
         * Base
         */
        base: string;
    };
    url: '/api/v1/offers/search';
};

export type SearchOffersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchOffersError = SearchOffersErrors[keyof SearchOffersErrors];

export type SearchOffersResponses = {
    /**
     * Successful Response
     */
    200: OffersPublic;
};

export type SearchOffersResponse = SearchOffersResponses[keyof SearchOffersResponses];

export type ReadUserOffersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/offers/user';
};

export type ReadUserOffersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserOffersError = ReadUserOffersErrors[keyof ReadUserOffersErrors];

export type ReadUserOffersResponses = {
    /**
     * Successful Response
     */
    200: OffersPublic;
};

export type ReadUserOffersResponse = ReadUserOffersResponses[keyof ReadUserOffersResponses];

export type LockOfferData = {
    body: OfferLockCreate;
    path?: never;
    query?: never;
    url: '/api/v1/offers/{offer_id}/lock';
};

export type LockOfferErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LockOfferError = LockOfferErrors[keyof LockOfferErrors];

export type LockOfferResponses = {
    /**
     * Successful Response
     */
    200: OfferLockRead;
};

export type LockOfferResponse = LockOfferResponses[keyof LockOfferResponses];

export type ReadCurrenciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/currencies/';
};

export type ReadCurrenciesResponses = {
    /**
     * Response Read Currencies
     *
     * Successful Response
     */
    200: Array<CurrencyRead>;
};

export type ReadCurrenciesResponse = ReadCurrenciesResponses[keyof ReadCurrenciesResponses];

export type ReadCurrencyBySymbolData = {
    body?: never;
    path: {
        /**
         * Symbol
         */
        symbol: string;
    };
    query?: never;
    url: '/api/v1/currencies/{symbol}';
};

export type ReadCurrencyBySymbolErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadCurrencyBySymbolError = ReadCurrencyBySymbolErrors[keyof ReadCurrencyBySymbolErrors];

export type ReadCurrencyBySymbolResponses = {
    /**
     * Response Read Currency By Symbol
     *
     * Successful Response
     */
    200: Array<CurrencyRead>;
};

export type ReadCurrencyBySymbolResponse = ReadCurrencyBySymbolResponses[keyof ReadCurrencyBySymbolResponses];

export type ReadTicketsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/tickets/';
};

export type ReadTicketsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTicketsError = ReadTicketsErrors[keyof ReadTicketsErrors];

export type ReadTicketsResponses = {
    /**
     * Successful Response
     */
    200: TicketsRead;
};

export type ReadTicketsResponse = ReadTicketsResponses[keyof ReadTicketsResponses];

export type CreateTicketData = {
    body: BodyCreateTicket;
    path?: never;
    query?: never;
    url: '/api/v1/tickets/';
};

export type CreateTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTicketError = CreateTicketErrors[keyof CreateTicketErrors];

export type CreateTicketResponses = {
    /**
     * Successful Response
     */
    200: TicketRead;
};

export type CreateTicketResponse = CreateTicketResponses[keyof CreateTicketResponses];

export type ReadTicketByIdData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}';
};

export type ReadTicketByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTicketByIdError = ReadTicketByIdErrors[keyof ReadTicketByIdErrors];

export type ReadTicketByIdResponses = {
    /**
     * Successful Response
     */
    200: TicketRead;
};

export type ReadTicketByIdResponse = ReadTicketByIdResponses[keyof ReadTicketByIdResponses];

export type UpdateTicketData = {
    body: TicketUpdate;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}';
};

export type UpdateTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTicketError = UpdateTicketErrors[keyof UpdateTicketErrors];

export type UpdateTicketResponses = {
    /**
     * Successful Response
     */
    200: TicketRead;
};

export type UpdateTicketResponse = UpdateTicketResponses[keyof UpdateTicketResponses];

export type ReadTicketMessagesData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/tickets/{ticket_id}/messages';
};

export type ReadTicketMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTicketMessagesError = ReadTicketMessagesErrors[keyof ReadTicketMessagesErrors];

export type ReadTicketMessagesResponses = {
    /**
     * Successful Response
     */
    200: TicketMessagesRead;
};

export type ReadTicketMessagesResponse = ReadTicketMessagesResponses[keyof ReadTicketMessagesResponses];

export type CreateTicketMessageData = {
    body: BodyCreateTicketMessage;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}/messages';
};

export type CreateTicketMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTicketMessageError = CreateTicketMessageErrors[keyof CreateTicketMessageErrors];

export type CreateTicketMessageResponses = {
    /**
     * Successful Response
     */
    200: TicketMessageRead;
};

export type CreateTicketMessageResponse = CreateTicketMessageResponses[keyof CreateTicketMessageResponses];

export type ReadPaymentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/payments/';
};

export type ReadPaymentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPaymentsError = ReadPaymentsErrors[keyof ReadPaymentsErrors];

export type ReadPaymentsResponses = {
    /**
     * Successful Response
     */
    200: PaymentsRead;
};

export type ReadPaymentsResponse = ReadPaymentsResponses[keyof ReadPaymentsResponses];

export type CreatePaymentData = {
    body?: BodyCreatePayment;
    path?: never;
    query: {
        /**
         * Invoice Id
         */
        invoice_id: string;
        payment_method: PaymentMethodEnum;
    };
    url: '/api/v1/payments/';
};

export type CreatePaymentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaymentError = CreatePaymentErrors[keyof CreatePaymentErrors];

export type CreatePaymentResponses = {
    /**
     * Successful Response
     */
    200: PaymentRead;
};

export type CreatePaymentResponse = CreatePaymentResponses[keyof CreatePaymentResponses];

export type ReadInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/payments/invoices';
};

export type ReadInvoicesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadInvoicesError = ReadInvoicesErrors[keyof ReadInvoicesErrors];

export type ReadInvoicesResponses = {
    /**
     * Successful Response
     */
    200: InvoicesRead;
};

export type ReadInvoicesResponse = ReadInvoicesResponses[keyof ReadInvoicesResponses];

export type CreateInvoiceData = {
    body: InvoiceCreateInput;
    path?: never;
    query?: never;
    url: '/api/v1/payments/invoices';
};

export type CreateInvoiceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInvoiceError = CreateInvoiceErrors[keyof CreateInvoiceErrors];

export type CreateInvoiceResponses = {
    /**
     * Successful Response
     */
    200: InvoiceCreateOutput;
};

export type CreateInvoiceResponse = CreateInvoiceResponses[keyof CreateInvoiceResponses];

export type ReadInvoiceByIdData = {
    body?: never;
    path: {
        /**
         * Invoice Id
         */
        invoice_id: string;
    };
    query?: never;
    url: '/api/v1/payments/invoices/{invoice_id}';
};

export type ReadInvoiceByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadInvoiceByIdError = ReadInvoiceByIdErrors[keyof ReadInvoiceByIdErrors];

export type ReadInvoiceByIdResponses = {
    /**
     * Successful Response
     */
    200: InvoiceRead;
};

export type ReadInvoiceByIdResponse = ReadInvoiceByIdResponses[keyof ReadInvoiceByIdResponses];

export type ReadReceiptByIdData = {
    body?: never;
    path: {
        /**
         * Payment Id
         */
        payment_id: string;
    };
    query?: never;
    url: '/api/v1/payments/receipts/{payment_id}';
};

export type ReadReceiptByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadReceiptByIdError = ReadReceiptByIdErrors[keyof ReadReceiptByIdErrors];

export type ReadReceiptByIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadKycDocumentTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/kyc/doc-types';
};

export type ReadKycDocumentTypesResponses = {
    /**
     * Response Read Kyc Document Types
     *
     * Successful Response
     */
    200: Array<KycDocumentTypeRead>;
};

export type ReadKycDocumentTypesResponse = ReadKycDocumentTypesResponses[keyof ReadKycDocumentTypesResponses];

export type CreateKycDocumentTypeData = {
    body: KycDocumentTypeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/kyc/doc-types';
};

export type CreateKycDocumentTypeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKycDocumentTypeError = CreateKycDocumentTypeErrors[keyof CreateKycDocumentTypeErrors];

export type CreateKycDocumentTypeResponses = {
    /**
     * Successful Response
     */
    200: KycDocumentTypeRead;
};

export type CreateKycDocumentTypeResponse = CreateKycDocumentTypeResponses[keyof CreateKycDocumentTypeResponses];

export type ReadKycDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filters
         *
         * A JSON string representing filter conditions.
         */
        filters?: string | null;
        /**
         * Sort
         *
         * e.g. name:asc or user__email:desc
         */
        sort?: string | null;
        /**
         * Search
         *
         * A string for global search across string fields.
         */
        search?: string | null;
        /**
         * Page
         *
         * Page number
         */
        page?: number;
        /**
         * Size
         *
         * Page size
         */
        size?: number;
    };
    url: '/api/v1/kyc/';
};

export type ReadKycDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadKycDocumentsError = ReadKycDocumentsErrors[keyof ReadKycDocumentsErrors];

export type ReadKycDocumentsResponses = {
    /**
     * Successful Response
     */
    200: PageKycDocumentRead;
};

export type ReadKycDocumentsResponse = ReadKycDocumentsResponses[keyof ReadKycDocumentsResponses];

export type CreateKycDocumentData = {
    body: BodyCreateKycDocument;
    path?: never;
    query?: never;
    url: '/api/v1/kyc/';
};

export type CreateKycDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKycDocumentError = CreateKycDocumentErrors[keyof CreateKycDocumentErrors];

export type CreateKycDocumentResponses = {
    /**
     * Successful Response
     */
    200: KycDocumentRead;
};

export type CreateKycDocumentResponse = CreateKycDocumentResponses[keyof CreateKycDocumentResponses];

export type ReadMyKycDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/kyc/my';
};

export type ReadMyKycDocumentsResponses = {
    /**
     * Response Read My Kyc Documents
     *
     * Successful Response
     */
    200: Array<KycDocumentRead>;
};

export type ReadMyKycDocumentsResponse = ReadMyKycDocumentsResponses[keyof ReadMyKycDocumentsResponses];

export type ReviewKycDocumentData = {
    body: KycDocumentReviewCreate;
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/api/v1/kyc/{doc_id}/review';
};

export type ReviewKycDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewKycDocumentError = ReviewKycDocumentErrors[keyof ReviewKycDocumentErrors];

export type ReviewKycDocumentResponses = {
    /**
     * Successful Response
     */
    200: KycDocumentRead;
};

export type ReviewKycDocumentResponse = ReviewKycDocumentResponses[keyof ReviewKycDocumentResponses];

export type SetRoleKycRequirementsData = {
    /**
     * Doc Type Ids
     */
    body: Array<string>;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/kyc/role-requirements/{role_id}';
};

export type SetRoleKycRequirementsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetRoleKycRequirementsError = SetRoleKycRequirementsErrors[keyof SetRoleKycRequirementsErrors];

export type SetRoleKycRequirementsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SetRoleKycRequirementsResponse = SetRoleKycRequirementsResponses[keyof SetRoleKycRequirementsResponses];

export type ReadFileByIdData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/api/v1/files/{file_id}';
};

export type ReadFileByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileByIdError = ReadFileByIdErrors[keyof ReadFileByIdErrors];

export type ReadFileByIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
