// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AppSettingRead
 */
export type AppSettingRead = {
    /**
     * Key
     */
    key: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Value
     */
    value: {
        [key: string]: unknown;
    } | Array<unknown> | string | number | number | boolean | null;
};

/**
 * AppSettings
 *
 * Central definition of application-level configuration.
 *
 * Each field in this model represents a single configurable setting and
 * maps to one record in the `AppSetting` database table.
 *
 * Defaults defined here are used as fallbacks and as initial values during
 * database synchronization.
 *
 * After adding, removing, or modifying fields in this model, run:
 *
 * python -m cli db sync
 *
 * to synchronize the definitions with the database.
 *
 * Notes:
 * - The setting name is derived from the field name by default.
 * - A custom name can be provided via `Field(title=...)`.
 * - Optional metadata such as descriptions should also be defined via `Field`.
 */
export type AppSettingsInput = {
    /**
     * Fiat Commission
     */
    fiat_commission?: number | string;
    /**
     * Crypto Commission
     */
    crypto_commission?: number | string;
    /**
     * Payment Currency
     */
    payment_currency_id?: number;
    /**
     * Pivot Currency
     *
     * Pivot currency ID used as the canonical reference for storing and deriving exchange rates. All rates are interpreted as `1 base_currency = rate * pivot_currency`.
     */
    pivot_currency_id?: number;
};

/**
 * AppSettings
 *
 * Central definition of application-level configuration.
 *
 * Each field in this model represents a single configurable setting and
 * maps to one record in the `AppSetting` database table.
 *
 * Defaults defined here are used as fallbacks and as initial values during
 * database synchronization.
 *
 * After adding, removing, or modifying fields in this model, run:
 *
 * python -m cli db sync
 *
 * to synchronize the definitions with the database.
 *
 * Notes:
 * - The setting name is derived from the field name by default.
 * - A custom name can be provided via `Field(title=...)`.
 * - Optional metadata such as descriptions should also be defined via `Field`.
 */
export type AppSettingsOutput = {
    /**
     * Fiat Commission
     */
    fiat_commission?: string;
    /**
     * Crypto Commission
     */
    crypto_commission?: string;
    /**
     * Payment Currency
     */
    payment_currency_id?: number;
    /**
     * Pivot Currency
     *
     * Pivot currency ID used as the canonical reference for storing and deriving exchange rates. All rates are interpreted as `1 base_currency = rate * pivot_currency`.
     */
    pivot_currency_id?: number;
};

/**
 * AttemptCreate
 */
export type AttemptCreate = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Exam Id
     */
    exam_id?: string | null;
    /**
     * Module Id
     */
    module_id: string;
    /**
     * Answers
     */
    answers: {
        [key: string]: string;
    };
    /**
     * Idempotency Key
     */
    idempotency_key: string;
};

/**
 * AttemptRead
 */
export type AttemptRead = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    exam: ExamRead;
    module: ModuleInfo;
    /**
     * Answers
     */
    answers: {
        [key: string]: string;
    };
    /**
     * Score
     */
    score: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Idempotency Key
     */
    idempotency_key: string;
};

/**
 * BlockchainRead
 */
export type BlockchainRead = {
    /**
     * Name
     */
    name: string;
};

/**
 * Body_add_files_to_ielts_module
 */
export type BodyAddFilesToIeltsModule = {
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * Body_create_kyc_document
 */
export type BodyCreateKycDocument = {
    /**
     * Doc Type Id
     */
    doc_type_id: number;
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * Body_create_payment
 */
export type BodyCreatePayment = {
    /**
     * Invoice Id
     */
    invoice_id: string;
    payment_method?: PaymentMethodEnum;
    /**
     * Receipt File
     */
    receipt_file?: Blob | File | null;
    /**
     * Receipt Test
     */
    receipt_test?: string | null;
};

/**
 * Body_create_role
 */
export type BodyCreateRole = {
    role_create: RoleCreate;
    /**
     * Permission Ids
     */
    permission_ids: Array<number>;
};

/**
 * Body_create_ticket
 */
export type BodyCreateTicket = {
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string | null;
    /**
     * Files
     */
    files?: Array<Blob | File>;
};

/**
 * Body_create_ticket_message
 */
export type BodyCreateTicketMessage = {
    /**
     * Message
     */
    message: string | null;
    /**
     * Files
     */
    files?: Array<Blob | File> | null;
};

/**
 * Body_login_access_token
 */
export type BodyLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_update_payment_status
 */
export type BodyUpdatePaymentStatus = {
    status: PaymentStatus;
};

/**
 * CurrencyRead
 */
export type CurrencyRead = {
    /**
     * Id
     */
    id: number;
    type: CurrencyType;
    /**
     * Name
     */
    name: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Sign
     */
    sign: string | null;
    /**
     * Decimals
     */
    decimals: number;
    /**
     * Logo
     */
    logo: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Token Std
     */
    token_std: string | null;
    blockchain: BlockchainRead | null;
    /**
     * Contract Address
     */
    contract_address: string | null;
    /**
     * Logo Url
     */
    readonly logo_url: string;
};

/**
 * CurrencyType
 */
export type CurrencyType = 'fiat' | 'crypto';

/**
 * ExamCreate
 */
export type ExamCreate = {
    /**
     * Code
     */
    code?: string | null;
    type: IeltsExamType;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Listening Id
     */
    listening_id?: string | null;
    /**
     * Reading Id
     */
    reading_id?: string | null;
    /**
     * Writing Id
     */
    writing_id?: string | null;
    /**
     * Speaking Id
     */
    speaking_id?: string | null;
};

/**
 * ExamRead
 */
export type ExamRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string | null;
    type: IeltsExamType;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Listening Id
     */
    listening_id: string | null;
    /**
     * Reading Id
     */
    reading_id: string | null;
    /**
     * Writing Id
     */
    writing_id: string | null;
    /**
     * Speaking Id
     */
    speaking_id: string | null;
};

/**
 * ExamUpdate
 */
export type ExamUpdate = {
    /**
     * Code
     */
    code?: string | null;
    type?: IeltsExamType | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Listening Id
     */
    listening_id?: string | null;
    /**
     * Reading Id
     */
    reading_id?: string | null;
    /**
     * Writing Id
     */
    writing_id?: string | null;
    /**
     * Speaking Id
     */
    speaking_id?: string | null;
};

/**
 * FileRead
 */
export type FileRead = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Filename
     */
    filename: string | null;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * Size
     */
    size: number | null;
};

/**
 * FileSetRead
 */
export type FileSetRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Files
     */
    files: Array<FileRead>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IdentifyInfoGroup
 */
export type IdentifyInfoGroupInput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'identify_info';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
    /**
     * Options Prompt
     */
    options_prompt?: string | null;
    /**
     * Options
     */
    options: {
        [key: string]: string;
    };
};

/**
 * IdentifyInfoGroup
 */
export type IdentifyInfoGroupOutput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'identify_info';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
    /**
     * Options Prompt
     */
    options_prompt?: string | null;
    /**
     * Options
     */
    options: {
        [key: string]: string;
    };
};

/**
 * IeltsExamType
 */
export type IeltsExamType = 'academic' | 'general';

/**
 * IeltsModuleType
 */
export type IeltsModuleType = 'listening' | 'reading' | 'writing' | 'speaking';

/**
 * Image
 */
export type Image = {
    /**
     * Type
     */
    type: 'image';
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * File
     */
    file: string;
};

/**
 * InvoiceCreate
 */
export type InvoiceCreateInput = {
    /**
     * Amount
     */
    amount: number | string;
    /**
     * Currency
     */
    currency: string;
    type: InvoiceType;
};

/**
 * InvoiceCreate
 */
export type InvoiceCreateOutput = {
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    type: InvoiceType;
};

/**
 * InvoiceRead
 */
export type InvoiceRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    type: InvoiceType;
    /**
     * Created At
     */
    created_at: string;
    status: InvoiceStatus;
    /**
     * Expires At
     */
    expires_at: string | null;
};

/**
 * InvoiceStatus
 *
 * Enum for the status of an invoice.
 */
export type InvoiceStatus = 'paid' | 'unpaid' | 'expired' | 'cancelled';

/**
 * InvoiceType
 */
export type InvoiceType = 'wallet_top_up' | 'offer_create_commission' | 'offer_lock_commission';

/**
 * InvoicesRead
 */
export type InvoicesRead = {
    /**
     * Data
     */
    data: Array<InvoiceRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * KycDocumentRead
 */
export type KycDocumentRead = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    type: KycDocumentTypeRead;
    file_set: FileSetRead;
    status: KycDocumentStatus;
    /**
     * Expires At
     */
    expires_at: string | null;
};

/**
 * KycDocumentReviewCreate
 */
export type KycDocumentReviewCreate = {
    action: KycReviewAction;
    /**
     * Rejection Reason
     */
    rejection_reason: string | null;
};

/**
 * KycDocumentStatus
 */
export type KycDocumentStatus = 'pending_review' | 'approved' | 'rejected' | 'expired';

/**
 * KycDocumentTypeCreate
 */
export type KycDocumentTypeCreate = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * KycDocumentTypeRead
 */
export type KycDocumentTypeRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * KycRequirementCreate
 *
 * Satisfying at least one requirement group is enough to assign the role.
 */
export type KycRequirementCreate = {
    /**
     * Groups
     */
    groups: Array<KycRequirementGroupCreate>;
};

/**
 * KycRequirementGroupCreate
 *
 * A requirement group: at least `required_count` distinct document types are required.
 * If `required_count` is None, all document types in the group are required.
 */
export type KycRequirementGroupCreate = {
    /**
     * Document Type Ids
     */
    document_type_ids: Array<number>;
    /**
     * Required Count
     */
    required_count?: number | null;
};

/**
 * KycReviewAction
 */
export type KycReviewAction = 'approve' | 'reject' | 'request_more_info' | 'expire';

/**
 * ListeningContent
 */
export type ListeningContentInput = {
    /**
     * Type
     */
    type?: 'listening';
    /**
     * Parts
     */
    parts: Array<ListeningSectionInput>;
};

/**
 * ListeningContent
 */
export type ListeningContentOutput = {
    /**
     * Type
     */
    type?: 'listening';
    /**
     * Parts
     */
    parts: Array<ListeningSectionOutput>;
};

/**
 * ListeningSection
 */
export type ListeningSectionInput = {
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Test
     */
    test: Array<({
        group_type: 'basic';
    } & QuestionGroupBaseInput) | ({
        group_type: 'multiple_choice';
    } & QuestionGroupMultiChoiceInput) | ({
        group_type: 'identify_info';
    } & IdentifyInfoGroupInput) | ({
        group_type: 'matching';
    } & MatchingInput) | ({
        group_type: 'completion_sentence';
    } & SentenceCompletionGroupInput) | ({
        group_type: 'completion_note';
    } & NoteCompletionGroupInput)>;
    /**
     * Audio File
     */
    audio_file: string;
    /**
     * Audio Script
     */
    audio_script: Array<Utterance>;
};

/**
 * ListeningSection
 */
export type ListeningSectionOutput = {
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Test
     */
    test: Array<({
        group_type: 'basic';
    } & QuestionGroupBaseOutput) | ({
        group_type: 'multiple_choice';
    } & QuestionGroupMultiChoiceOutput) | ({
        group_type: 'identify_info';
    } & IdentifyInfoGroupOutput) | ({
        group_type: 'matching';
    } & MatchingOutput) | ({
        group_type: 'completion_sentence';
    } & SentenceCompletionGroupOutput) | ({
        group_type: 'completion_note';
    } & NoteCompletionGroupOutput)>;
    /**
     * Audio File
     */
    audio_file: string;
    /**
     * Audio Script
     */
    audio_script: Array<Utterance>;
};

/**
 * Maker
 */
export type Maker = {
    profile: ProfilePublic;
    /**
     * Username
     */
    username: string;
};

/**
 * Matching
 */
export type MatchingInput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'matching';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
    /**
     * Source Title
     */
    source_title?: string | null;
    /**
     * Source
     */
    source?: Array<string> | null;
};

/**
 * Matching
 */
export type MatchingOutput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'matching';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
    /**
     * Source Title
     */
    source_title?: string | null;
    /**
     * Source
     */
    source?: Array<string> | null;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * ModuleCreate
 */
export type ModuleCreate = {
    type: IeltsModuleType;
    /**
     * Tag
     */
    tag?: string | null;
    /**
     * Duration Minutes
     */
    duration_minutes: number;
    /**
     * Questions
     */
    questions?: {
        [key: string]: Question;
    } | null;
    /**
     * Content
     */
    content: ({
        type: 'listening';
    } & ListeningContentInput) | ({
        type: 'reading';
    } & ReadingContentInput) | ({
        type: 'writing';
    } & WritingContentInput) | ({
        type: 'speaking';
    } & SpeakingContent);
};

/**
 * ModuleInfo
 */
export type ModuleInfo = {
    /**
     * Id
     */
    id: string;
    type: IeltsModuleType;
    /**
     * Tag
     */
    tag: string | null;
};

/**
 * ModuleRead
 */
export type ModuleRead = {
    /**
     * Id
     */
    id: string;
    type: IeltsModuleType;
    /**
     * Tag
     */
    tag: string | null;
    /**
     * Duration Minutes
     */
    duration_minutes: number;
    file_set: FileSetRead | null;
    /**
     * Questions
     */
    questions: {
        [key: string]: Question;
    } | null;
    /**
     * Content
     */
    content: ({
        type: 'listening';
    } & ListeningContentOutput) | ({
        type: 'reading';
    } & ReadingContentOutput) | ({
        type: 'writing';
    } & WritingContentOutput) | ({
        type: 'speaking';
    } & SpeakingContent) | null;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * NoteCompletionGroup
 */
export type NoteCompletionGroupInput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'completion_note';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
    /**
     * Options
     */
    options?: Array<string> | null;
    /**
     * Content
     */
    content: ({
        type: 'table';
    } & Table) | ({
        type: 'text';
    } & Text);
};

/**
 * NoteCompletionGroup
 */
export type NoteCompletionGroupOutput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'completion_note';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
    /**
     * Options
     */
    options?: Array<string> | null;
    /**
     * Content
     */
    content: ({
        type: 'table';
    } & Table) | ({
        type: 'text';
    } & Text);
};

/**
 * OfferCreate
 */
export type OfferCreate = {
    /**
     * Sell Asset Id
     */
    sell_asset_id: number;
    /**
     * Buy Asset Id
     */
    buy_asset_id: number;
    /**
     * Quote
     */
    quote: number | string;
    /**
     * Total Amount
     */
    total_amount: number | string;
    /**
     * Min Lock Amount
     */
    min_lock_amount?: number | string | null;
    /**
     * Max Lock Amount
     */
    max_lock_amount?: number | string | null;
    /**
     * Expires At
     */
    expires_at: string | null;
};

/**
 * OfferLockCreate
 */
export type OfferLockCreate = {
    /**
     * Locked Amount
     */
    locked_amount: number | string;
};

/**
 * OfferLockRead
 */
export type OfferLockRead = {
    /**
     * Id
     */
    id: string;
};

/**
 * OfferPublic
 */
export type OfferPublic = {
    /**
     * Id
     */
    id: string;
    maker: Maker;
    sell: CurrencyRead;
    buy: CurrencyRead;
    /**
     * Price
     */
    readonly price: string;
    /**
     * Total Amount
     */
    readonly total_amount: string;
    /**
     * Min Lock Amount
     */
    readonly min_lock_amount: string;
    /**
     * Available Amount
     */
    readonly available_amount: string;
};

/**
 * OffersPublic
 */
export type OffersPublic = {
    /**
     * Data
     */
    data: Array<OfferPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Page[KycDocumentRead]
 */
export type PageKycDocumentRead = {
    /**
     * Items
     */
    items: Array<KycDocumentRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * Passage
 */
export type Passage = {
    /**
     * Title
     */
    title: string;
    /**
     * Subtitle
     */
    subtitle?: string | null;
    /**
     * Sections
     */
    sections: Array<PassageSection>;
    /**
     * Footnotes
     */
    footnotes?: Array<string> | null;
};

/**
 * PassageSection
 */
export type PassageSection = {
    /**
     * Label
     */
    label?: string | null;
    /**
     * Text
     */
    text: Array<string>;
};

/**
 * PaymentMethodEnum
 */
export type PaymentMethodEnum = 'crypto' | 'paypal' | 'wallet' | 'bank_transfer';

/**
 * PaymentRead
 */
export type PaymentRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Invoice Id
     */
    invoice_id: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency Id
     */
    currency_id: number;
    status: PaymentStatus;
    receipt_file_set: FileSetRead | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PaymentStatus
 *
 * Enum for the status of a payment.
 */
export type PaymentStatus = 'pending' | 'success' | 'failed';

/**
 * PaymentsRead
 */
export type PaymentsRead = {
    /**
     * Data
     */
    data: Array<PaymentRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * PermissionDomainRead
 */
export type PermissionDomainRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Permissions
     */
    permissions: Array<PermissionRead>;
};

/**
 * PermissionRead
 */
export type PermissionRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string | null;
};

/**
 * ProfilePublic
 */
export type ProfilePublic = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar
     */
    avatar?: string | null;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Avatar Url
     */
    readonly avatar_url: string;
};

/**
 * Question
 */
export type Question = {
    /**
     * Type
     */
    type: 'question';
    /**
     * Id
     */
    id: string;
    question_type: QuestionType;
    /**
     * Question
     */
    question?: Array<string> | string | null;
    /**
     * Choices
     */
    choices?: Array<string> | null;
    /**
     * Answer
     */
    answer?: Array<string> | string | null;
};

/**
 * QuestionGroupBase
 */
export type QuestionGroupBaseInput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type?: 'basic';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
};

/**
 * QuestionGroupBase
 */
export type QuestionGroupBaseOutput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type?: 'basic';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
};

/**
 * QuestionGroupMultiChoice
 */
export type QuestionGroupMultiChoiceInput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'multiple_choice';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
};

/**
 * QuestionGroupMultiChoice
 */
export type QuestionGroupMultiChoiceOutput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'multiple_choice';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
};

/**
 * QuestionType
 */
export type QuestionType = 'multiple_choice' | 'completion' | 'short_answer' | 'identify_info' | 'matching';

/**
 * ReadingContent
 */
export type ReadingContentInput = {
    /**
     * Type
     */
    type?: 'reading';
    /**
     * Parts
     */
    parts: Array<ReadingSectionInput>;
};

/**
 * ReadingContent
 */
export type ReadingContentOutput = {
    /**
     * Type
     */
    type?: 'reading';
    /**
     * Parts
     */
    parts: Array<ReadingSectionOutput>;
};

/**
 * ReadingSection
 */
export type ReadingSectionInput = {
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Test
     */
    test: Array<({
        group_type: 'basic';
    } & QuestionGroupBaseInput) | ({
        group_type: 'multiple_choice';
    } & QuestionGroupMultiChoiceInput) | ({
        group_type: 'identify_info';
    } & IdentifyInfoGroupInput) | ({
        group_type: 'matching';
    } & MatchingInput) | ({
        group_type: 'completion_sentence';
    } & SentenceCompletionGroupInput) | ({
        group_type: 'completion_note';
    } & NoteCompletionGroupInput)>;
    /**
     * Prompt
     */
    prompt: Array<string>;
    passage: Passage;
};

/**
 * ReadingSection
 */
export type ReadingSectionOutput = {
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Test
     */
    test: Array<({
        group_type: 'basic';
    } & QuestionGroupBaseOutput) | ({
        group_type: 'multiple_choice';
    } & QuestionGroupMultiChoiceOutput) | ({
        group_type: 'identify_info';
    } & IdentifyInfoGroupOutput) | ({
        group_type: 'matching';
    } & MatchingOutput) | ({
        group_type: 'completion_sentence';
    } & SentenceCompletionGroupOutput) | ({
        group_type: 'completion_note';
    } & NoteCompletionGroupOutput)>;
    /**
     * Prompt
     */
    prompt: Array<string>;
    passage: Passage;
};

/**
 * RoleCreate
 */
export type RoleCreate = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * RoleRead
 */
export type RoleRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Permissions
     */
    permissions: Array<PermissionRead>;
};

/**
 * SentenceCompletionGroup
 */
export type SentenceCompletionGroupInput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'completion_sentence';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
    /**
     * Options
     */
    options?: Array<string> | null;
};

/**
 * SentenceCompletionGroup
 */
export type SentenceCompletionGroupOutput = {
    /**
     * Type
     */
    type: 'question_group';
    /**
     * Group Type
     */
    group_type: 'completion_sentence';
    /**
     * Question Range
     */
    question_range?: [
        number,
        number
    ] | null;
    /**
     * Prompt
     */
    prompt?: Array<string> | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Questions
     */
    questions: Array<Question>;
    /**
     * Options
     */
    options?: Array<string> | null;
};

/**
 * SpeakingContent
 */
export type SpeakingContent = {
    /**
     * Type
     */
    type?: 'speaking';
    part1: SpeakingQuestionGroup;
    part2: SpeakingCueCard;
    /**
     * Part3
     */
    part3: Array<SpeakingQuestionGroup>;
};

/**
 * SpeakingCueCard
 */
export type SpeakingCueCard = {
    /**
     * First Paragraph
     */
    first_paragraph: string;
    /**
     * Instructions
     */
    instructions: Array<string>;
    /**
     * Last Paragraph
     */
    last_paragraph?: string | null;
};

/**
 * SpeakingQuestionGroup
 */
export type SpeakingQuestionGroup = {
    /**
     * Title
     */
    title: string;
    /**
     * Questions
     */
    questions: Array<string>;
};

/**
 * Table
 */
export type Table = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Type
     */
    type: 'table';
    /**
     * Rows
     */
    rows: Array<Array<string>>;
};

/**
 * Text
 */
export type Text = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Type
     */
    type: 'text';
    /**
     * Text
     */
    text: Array<string>;
};

/**
 * TicketMessageRead
 */
export type TicketMessageRead = {
    /**
     * Id
     */
    id: string;
    sender: TicketSender;
    /**
     * Message
     */
    message: string | null;
    file_set: FileSetRead | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TicketMessagesRead
 */
export type TicketMessagesRead = {
    /**
     * Data
     */
    data: Array<TicketMessageRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * TicketRead
 */
export type TicketRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Subject
     */
    subject: string;
    status: TicketStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TicketSender
 */
export type TicketSender = {
    /**
     * Username
     */
    username: string;
};

/**
 * TicketStatus
 */
export type TicketStatus = 'open' | 'closed';

/**
 * TicketUpdate
 */
export type TicketUpdate = {
    status: TicketStatus;
};

/**
 * TicketsRead
 */
export type TicketsRead = {
    /**
     * Data
     */
    data: Array<TicketRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
};

/**
 * UserMe
 */
export type UserMe = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    profile?: ProfilePublic | null;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Utterance
 */
export type Utterance = {
    /**
     * Speaker
     */
    speaker?: string | null;
    /**
     * Text
     */
    text: string;
    /**
     * Questions
     */
    questions?: Array<string> | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WritingContent
 */
export type WritingContentInput = {
    /**
     * Type
     */
    type?: 'writing';
    /**
     * Tasks
     */
    tasks: Array<WritingTask>;
};

/**
 * WritingContent
 */
export type WritingContentOutput = {
    /**
     * Type
     */
    type?: 'writing';
    /**
     * Tasks
     */
    tasks: Array<WritingTask>;
};

/**
 * WritingTask
 */
export type WritingTask = {
    /**
     * Question
     */
    question: Array<string>;
    /**
     * Visuals
     */
    visuals?: Array<({
        type: 'image';
    } & Image) | ({
        type: 'table';
    } & Table)> | null;
    /**
     * Sample Answer
     */
    sample_answer: Array<string>;
};

/**
 * CurrencyRead
 */
export type CurrencyReadWritable = {
    /**
     * Id
     */
    id: number;
    type: CurrencyType;
    /**
     * Name
     */
    name: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Sign
     */
    sign: string | null;
    /**
     * Decimals
     */
    decimals: number;
    /**
     * Logo
     */
    logo: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Token Std
     */
    token_std: string | null;
    blockchain: BlockchainRead | null;
    /**
     * Contract Address
     */
    contract_address: string | null;
};

/**
 * Maker
 */
export type MakerWritable = {
    profile: ProfilePublicWritable;
    /**
     * Username
     */
    username: string;
};

/**
 * OfferPublic
 */
export type OfferPublicWritable = {
    /**
     * Id
     */
    id: string;
    maker: MakerWritable;
    sell: CurrencyReadWritable;
    buy: CurrencyReadWritable;
};

/**
 * OffersPublic
 */
export type OffersPublicWritable = {
    /**
     * Data
     */
    data: Array<OfferPublicWritable>;
    /**
     * Count
     */
    count: number;
};

/**
 * ProfilePublic
 */
export type ProfilePublicWritable = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar
     */
    avatar?: string | null;
};

/**
 * UserMe
 */
export type UserMeWritable = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    profile?: ProfilePublicWritable | null;
};

export type ReadSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/';
};

export type ReadSettingsResponses = {
    /**
     * Response Read Settings
     *
     * Successful Response
     */
    200: Array<AppSettingRead>;
};

export type ReadSettingsResponse = ReadSettingsResponses[keyof ReadSettingsResponses];

export type UpdateSettingsData = {
    body: AppSettingsInput;
    path?: never;
    query?: never;
    url: '/api/v1/settings/';
};

export type UpdateSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    /**
     * Successful Response
     */
    200: AppSettingsOutput;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type ReadPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rbac/permissions';
};

export type ReadPermissionsResponses = {
    /**
     * Response Read Permissions
     *
     * Successful Response
     */
    200: Array<PermissionDomainRead>;
};

export type ReadPermissionsResponse = ReadPermissionsResponses[keyof ReadPermissionsResponses];

export type ReadRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rbac/roles';
};

export type ReadRolesResponses = {
    /**
     * Response Read Roles
     *
     * Successful Response
     */
    200: Array<RoleRead>;
};

export type ReadRolesResponse = ReadRolesResponses[keyof ReadRolesResponses];

export type CreateRoleData = {
    body: BodyCreateRole;
    path?: never;
    query?: never;
    url: '/api/v1/rbac/roles';
};

export type CreateRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoleError = CreateRoleErrors[keyof CreateRoleErrors];

export type CreateRoleResponses = {
    /**
     * Successful Response
     */
    200: RoleRead;
};

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses];

export type ReadUserRolesData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/rbac/roles/{user_id}';
};

export type ReadUserRolesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserRolesError = ReadUserRolesErrors[keyof ReadUserRolesErrors];

export type ReadUserRolesResponses = {
    /**
     * Response Read User Roles
     *
     * Successful Response
     */
    200: Array<RoleRead>;
};

export type ReadUserRolesResponse = ReadUserRolesResponses[keyof ReadUserRolesResponses];

export type DeleteRoleData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: number;
    };
    query?: never;
    url: '/api/v1/rbac/roles/{role_id}';
};

export type DeleteRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRoleError = DeleteRoleErrors[keyof DeleteRoleErrors];

export type DeleteRoleResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteRoleResponse = DeleteRoleResponses[keyof DeleteRoleResponses];

export type UpdateRoleData = {
    /**
     * Permission Ids
     */
    body: Array<number>;
    path: {
        /**
         * Role Id
         */
        role_id: number;
    };
    query?: never;
    url: '/api/v1/rbac/roles/{role_id}';
};

export type UpdateRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors];

export type UpdateRoleResponses = {
    /**
     * Successful Response
     */
    200: RoleRead;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];

export type LoginAccessTokenData = {
    body: BodyLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenError = LoginAccessTokenErrors[keyof LoginAccessTokenErrors];

export type LoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenResponse = LoginAccessTokenResponses[keyof LoginAccessTokenResponses];

export type TestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type TestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type TestTokenResponse = TestTokenResponses[keyof TestTokenResponses];

export type RecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type RecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordError = RecoverPasswordErrors[keyof RecoverPasswordErrors];

export type RecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RecoverPasswordResponse = RecoverPasswordResponses[keyof RecoverPasswordResponses];

export type ResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type ResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type RecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type RecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordHtmlContentError = RecoverPasswordHtmlContentErrors[keyof RecoverPasswordHtmlContentErrors];

export type RecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type RecoverPasswordHtmlContentResponse = RecoverPasswordHtmlContentResponses[keyof RecoverPasswordHtmlContentResponses];

export type ReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type ReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersError = ReadUsersErrors[keyof ReadUsersErrors];

export type ReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type ReadUsersResponse = ReadUsersResponses[keyof ReadUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type DeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserMeResponse = DeleteUserMeResponses[keyof DeleteUserMeResponses];

export type ReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserMe;
};

export type ReadUserMeResponse = ReadUserMeResponses[keyof ReadUserMeResponses];

export type UpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeError = UpdateUserMeErrors[keyof UpdateUserMeErrors];

export type UpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserMe;
};

export type UpdateUserMeResponse = UpdateUserMeResponses[keyof UpdateUserMeResponses];

export type UpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordMeError = UpdatePasswordMeErrors[keyof UpdatePasswordMeErrors];

export type UpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UpdatePasswordMeResponse = UpdatePasswordMeResponses[keyof UpdatePasswordMeResponses];

export type RegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdError = ReadUserByIdErrors[keyof ReadUserByIdErrors];

export type ReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByIdResponse = ReadUserByIdResponses[keyof ReadUserByIdResponses];

export type UpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type TestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type TestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestEmailError = TestEmailErrors[keyof TestEmailErrors];

export type TestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type TestEmailResponse = TestEmailResponses[keyof TestEmailResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type HealthCheckResponses = {
    /**
     * Response Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type ReadOffersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/offers/';
};

export type ReadOffersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadOffersError = ReadOffersErrors[keyof ReadOffersErrors];

export type ReadOffersResponses = {
    /**
     * Successful Response
     */
    200: OffersPublic;
};

export type ReadOffersResponse = ReadOffersResponses[keyof ReadOffersResponses];

export type CreateOfferData = {
    body: OfferCreate;
    path?: never;
    query?: never;
    url: '/api/v1/offers/';
};

export type CreateOfferErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOfferError = CreateOfferErrors[keyof CreateOfferErrors];

export type CreateOfferResponses = {
    /**
     * Successful Response
     */
    200: OfferPublic;
};

export type CreateOfferResponse = CreateOfferResponses[keyof CreateOfferResponses];

export type SearchOffersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Type
         */
        type: 'buy' | 'sell';
        /**
         * Target
         */
        target: string;
        /**
         * Amount
         */
        amount: number | string;
        /**
         * Base
         */
        base: string;
    };
    url: '/api/v1/offers/search';
};

export type SearchOffersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchOffersError = SearchOffersErrors[keyof SearchOffersErrors];

export type SearchOffersResponses = {
    /**
     * Successful Response
     */
    200: OffersPublic;
};

export type SearchOffersResponse = SearchOffersResponses[keyof SearchOffersResponses];

export type ReadUserOffersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/offers/user';
};

export type ReadUserOffersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserOffersError = ReadUserOffersErrors[keyof ReadUserOffersErrors];

export type ReadUserOffersResponses = {
    /**
     * Successful Response
     */
    200: OffersPublic;
};

export type ReadUserOffersResponse = ReadUserOffersResponses[keyof ReadUserOffersResponses];

export type LockOfferData = {
    body: OfferLockCreate;
    path: {
        /**
         * Offer Id
         */
        offer_id: string;
    };
    query?: never;
    url: '/api/v1/offers/{offer_id}/lock';
};

export type LockOfferErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LockOfferError = LockOfferErrors[keyof LockOfferErrors];

export type LockOfferResponses = {
    /**
     * Successful Response
     */
    200: OfferLockRead;
};

export type LockOfferResponse = LockOfferResponses[keyof LockOfferResponses];

export type ReadCurrenciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/currencies/';
};

export type ReadCurrenciesResponses = {
    /**
     * Response Read Currencies
     *
     * Successful Response
     */
    200: Array<CurrencyRead>;
};

export type ReadCurrenciesResponse = ReadCurrenciesResponses[keyof ReadCurrenciesResponses];

export type ReadCurrencyBySymbolData = {
    body?: never;
    path: {
        /**
         * Symbol
         */
        symbol: string;
    };
    query?: never;
    url: '/api/v1/currencies/{symbol}';
};

export type ReadCurrencyBySymbolErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadCurrencyBySymbolError = ReadCurrencyBySymbolErrors[keyof ReadCurrencyBySymbolErrors];

export type ReadCurrencyBySymbolResponses = {
    /**
     * Response Read Currency By Symbol
     *
     * Successful Response
     */
    200: Array<CurrencyRead>;
};

export type ReadCurrencyBySymbolResponse = ReadCurrencyBySymbolResponses[keyof ReadCurrencyBySymbolResponses];

export type ReadTicketsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/tickets/';
};

export type ReadTicketsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTicketsError = ReadTicketsErrors[keyof ReadTicketsErrors];

export type ReadTicketsResponses = {
    /**
     * Successful Response
     */
    200: TicketsRead;
};

export type ReadTicketsResponse = ReadTicketsResponses[keyof ReadTicketsResponses];

export type CreateTicketData = {
    body: BodyCreateTicket;
    path?: never;
    query?: never;
    url: '/api/v1/tickets/';
};

export type CreateTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTicketError = CreateTicketErrors[keyof CreateTicketErrors];

export type CreateTicketResponses = {
    /**
     * Successful Response
     */
    200: TicketRead;
};

export type CreateTicketResponse = CreateTicketResponses[keyof CreateTicketResponses];

export type ReadTicketByIdData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}';
};

export type ReadTicketByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTicketByIdError = ReadTicketByIdErrors[keyof ReadTicketByIdErrors];

export type ReadTicketByIdResponses = {
    /**
     * Successful Response
     */
    200: TicketRead;
};

export type ReadTicketByIdResponse = ReadTicketByIdResponses[keyof ReadTicketByIdResponses];

export type UpdateTicketData = {
    body: TicketUpdate;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}';
};

export type UpdateTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTicketError = UpdateTicketErrors[keyof UpdateTicketErrors];

export type UpdateTicketResponses = {
    /**
     * Successful Response
     */
    200: TicketRead;
};

export type UpdateTicketResponse = UpdateTicketResponses[keyof UpdateTicketResponses];

export type ReadTicketMessagesData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/tickets/{ticket_id}/messages';
};

export type ReadTicketMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTicketMessagesError = ReadTicketMessagesErrors[keyof ReadTicketMessagesErrors];

export type ReadTicketMessagesResponses = {
    /**
     * Successful Response
     */
    200: TicketMessagesRead;
};

export type ReadTicketMessagesResponse = ReadTicketMessagesResponses[keyof ReadTicketMessagesResponses];

export type CreateTicketMessageData = {
    body: BodyCreateTicketMessage;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}/messages';
};

export type CreateTicketMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTicketMessageError = CreateTicketMessageErrors[keyof CreateTicketMessageErrors];

export type CreateTicketMessageResponses = {
    /**
     * Successful Response
     */
    200: TicketMessageRead;
};

export type CreateTicketMessageResponse = CreateTicketMessageResponses[keyof CreateTicketMessageResponses];

export type ReadPaymentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/payments/';
};

export type ReadPaymentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPaymentsError = ReadPaymentsErrors[keyof ReadPaymentsErrors];

export type ReadPaymentsResponses = {
    /**
     * Successful Response
     */
    200: PaymentsRead;
};

export type ReadPaymentsResponse = ReadPaymentsResponses[keyof ReadPaymentsResponses];

export type CreatePaymentData = {
    body: BodyCreatePayment;
    path?: never;
    query?: never;
    url: '/api/v1/payments/';
};

export type CreatePaymentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaymentError = CreatePaymentErrors[keyof CreatePaymentErrors];

export type CreatePaymentResponses = {
    /**
     * Successful Response
     */
    200: PaymentRead;
};

export type CreatePaymentResponse = CreatePaymentResponses[keyof CreatePaymentResponses];

export type ReadInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/payments/invoices';
};

export type ReadInvoicesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadInvoicesError = ReadInvoicesErrors[keyof ReadInvoicesErrors];

export type ReadInvoicesResponses = {
    /**
     * Successful Response
     */
    200: InvoicesRead;
};

export type ReadInvoicesResponse = ReadInvoicesResponses[keyof ReadInvoicesResponses];

export type CreateInvoiceData = {
    body: InvoiceCreateInput;
    path?: never;
    query?: never;
    url: '/api/v1/payments/invoices';
};

export type CreateInvoiceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInvoiceError = CreateInvoiceErrors[keyof CreateInvoiceErrors];

export type CreateInvoiceResponses = {
    /**
     * Successful Response
     */
    200: InvoiceCreateOutput;
};

export type CreateInvoiceResponse = CreateInvoiceResponses[keyof CreateInvoiceResponses];

export type ReadInvoiceByIdData = {
    body?: never;
    path: {
        /**
         * Invoice Id
         */
        invoice_id: string;
    };
    query?: never;
    url: '/api/v1/payments/invoices/{invoice_id}';
};

export type ReadInvoiceByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadInvoiceByIdError = ReadInvoiceByIdErrors[keyof ReadInvoiceByIdErrors];

export type ReadInvoiceByIdResponses = {
    /**
     * Successful Response
     */
    200: InvoiceRead;
};

export type ReadInvoiceByIdResponse = ReadInvoiceByIdResponses[keyof ReadInvoiceByIdResponses];

export type ReadReceiptByIdData = {
    body?: never;
    path: {
        /**
         * Payment Id
         */
        payment_id: string;
    };
    query?: never;
    url: '/api/v1/payments/receipts/{payment_id}';
};

export type ReadReceiptByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadReceiptByIdError = ReadReceiptByIdErrors[keyof ReadReceiptByIdErrors];

export type ReadReceiptByIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdatePaymentStatusData = {
    body: BodyUpdatePaymentStatus;
    path: {
        /**
         * Payment Id
         */
        payment_id: string;
    };
    query?: never;
    url: '/api/v1/payments/{payment_id}';
};

export type UpdatePaymentStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePaymentStatusError = UpdatePaymentStatusErrors[keyof UpdatePaymentStatusErrors];

export type UpdatePaymentStatusResponses = {
    /**
     * Successful Response
     */
    200: PaymentRead;
};

export type UpdatePaymentStatusResponse = UpdatePaymentStatusResponses[keyof UpdatePaymentStatusResponses];

export type ReadKycDocumentTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/kyc/doc-types';
};

export type ReadKycDocumentTypesResponses = {
    /**
     * Response Read Kyc Document Types
     *
     * Successful Response
     */
    200: Array<KycDocumentTypeRead>;
};

export type ReadKycDocumentTypesResponse = ReadKycDocumentTypesResponses[keyof ReadKycDocumentTypesResponses];

export type CreateKycDocumentTypeData = {
    body: KycDocumentTypeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/kyc/doc-types';
};

export type CreateKycDocumentTypeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKycDocumentTypeError = CreateKycDocumentTypeErrors[keyof CreateKycDocumentTypeErrors];

export type CreateKycDocumentTypeResponses = {
    /**
     * Successful Response
     */
    200: KycDocumentTypeRead;
};

export type CreateKycDocumentTypeResponse = CreateKycDocumentTypeResponses[keyof CreateKycDocumentTypeResponses];

export type ReadKycDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filters
         *
         * A JSON string representing filter conditions.
         */
        filters?: string | null;
        /**
         * Sort
         *
         * e.g. name:asc or user__email:desc
         */
        sort?: string | null;
        /**
         * Search
         *
         * A string for global search across string fields.
         */
        search?: string | null;
        /**
         * Page
         *
         * Page number
         */
        page?: number;
        /**
         * Size
         *
         * Page size
         */
        size?: number;
    };
    url: '/api/v1/kyc/documents';
};

export type ReadKycDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadKycDocumentsError = ReadKycDocumentsErrors[keyof ReadKycDocumentsErrors];

export type ReadKycDocumentsResponses = {
    /**
     * Successful Response
     */
    200: PageKycDocumentRead;
};

export type ReadKycDocumentsResponse = ReadKycDocumentsResponses[keyof ReadKycDocumentsResponses];

export type CreateKycDocumentData = {
    body: BodyCreateKycDocument;
    path?: never;
    query?: never;
    url: '/api/v1/kyc/documents';
};

export type CreateKycDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKycDocumentError = CreateKycDocumentErrors[keyof CreateKycDocumentErrors];

export type CreateKycDocumentResponses = {
    /**
     * Successful Response
     */
    200: KycDocumentRead;
};

export type CreateKycDocumentResponse = CreateKycDocumentResponses[keyof CreateKycDocumentResponses];

export type ReadMyKycDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/kyc/me/documents';
};

export type ReadMyKycDocumentsResponses = {
    /**
     * Response Read My Kyc Documents
     *
     * Successful Response
     */
    200: Array<KycDocumentRead>;
};

export type ReadMyKycDocumentsResponse = ReadMyKycDocumentsResponses[keyof ReadMyKycDocumentsResponses];

export type ReviewKycDocumentData = {
    body: KycDocumentReviewCreate;
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/api/v1/kyc/documents/{doc_id}/review';
};

export type ReviewKycDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewKycDocumentError = ReviewKycDocumentErrors[keyof ReviewKycDocumentErrors];

export type ReviewKycDocumentResponses = {
    /**
     * Successful Response
     */
    200: KycDocumentRead;
};

export type ReviewKycDocumentResponse = ReviewKycDocumentResponses[keyof ReviewKycDocumentResponses];

export type SetRoleKycRequirementsData = {
    body: KycRequirementCreate;
    path: {
        /**
         * Role Id
         */
        role_id: number;
    };
    query?: never;
    url: '/api/v1/kyc/role-requirements/{role_id}';
};

export type SetRoleKycRequirementsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetRoleKycRequirementsError = SetRoleKycRequirementsErrors[keyof SetRoleKycRequirementsErrors];

export type SetRoleKycRequirementsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SetRoleKycRequirementsResponse = SetRoleKycRequirementsResponses[keyof SetRoleKycRequirementsResponses];

export type DeleteFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/api/v1/files/{file_id}';
};

export type DeleteFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFileError = DeleteFileErrors[keyof DeleteFileErrors];

export type DeleteFileResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteFileResponse = DeleteFileResponses[keyof DeleteFileResponses];

export type GetFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/api/v1/files/{file_id}';
};

export type GetFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadFileSetData = {
    body?: never;
    path: {
        /**
         * File Set Id
         */
        file_set_id: string;
    };
    query?: never;
    url: '/api/v1/files/set/{file_set_id}';
};

export type ReadFileSetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileSetError = ReadFileSetErrors[keyof ReadFileSetErrors];

export type ReadFileSetResponses = {
    /**
     * Successful Response
     */
    200: FileSetRead;
};

export type ReadFileSetResponse = ReadFileSetResponses[keyof ReadFileSetResponses];

export type ReadIeltsExamsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ielts/exams';
};

export type ReadIeltsExamsResponses = {
    /**
     * Response Read Ielts Exams
     *
     * Successful Response
     */
    200: Array<ExamRead>;
};

export type ReadIeltsExamsResponse = ReadIeltsExamsResponses[keyof ReadIeltsExamsResponses];

export type CreateIeltsExamData = {
    body: ExamCreate;
    path?: never;
    query?: never;
    url: '/api/v1/ielts/exams';
};

export type CreateIeltsExamErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateIeltsExamError = CreateIeltsExamErrors[keyof CreateIeltsExamErrors];

export type CreateIeltsExamResponses = {
    /**
     * Successful Response
     */
    200: ExamRead;
};

export type CreateIeltsExamResponse = CreateIeltsExamResponses[keyof CreateIeltsExamResponses];

export type ReadIeltsExamByIdData = {
    body?: never;
    path: {
        /**
         * Exam Id
         */
        exam_id: string;
    };
    query?: never;
    url: '/api/v1/ielts/exams/{exam_id}';
};

export type ReadIeltsExamByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadIeltsExamByIdError = ReadIeltsExamByIdErrors[keyof ReadIeltsExamByIdErrors];

export type ReadIeltsExamByIdResponses = {
    /**
     * Successful Response
     */
    200: ExamRead;
};

export type ReadIeltsExamByIdResponse = ReadIeltsExamByIdResponses[keyof ReadIeltsExamByIdResponses];

export type UpdateIeltsExamData = {
    body: ExamUpdate;
    path: {
        /**
         * Exam Id
         */
        exam_id: string;
    };
    query?: never;
    url: '/api/v1/ielts/exams/{exam_id}';
};

export type UpdateIeltsExamErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateIeltsExamError = UpdateIeltsExamErrors[keyof UpdateIeltsExamErrors];

export type UpdateIeltsExamResponses = {
    /**
     * Successful Response
     */
    200: ExamRead;
};

export type UpdateIeltsExamResponse = UpdateIeltsExamResponses[keyof UpdateIeltsExamResponses];

export type ReadIeltsModulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ielts/modules';
};

export type ReadIeltsModulesResponses = {
    /**
     * Response Read Ielts Modules
     *
     * Successful Response
     */
    200: Array<ModuleInfo>;
};

export type ReadIeltsModulesResponse = ReadIeltsModulesResponses[keyof ReadIeltsModulesResponses];

export type CreateIeltsModuleData = {
    body: ModuleCreate;
    path?: never;
    query?: never;
    url: '/api/v1/ielts/modules';
};

export type CreateIeltsModuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateIeltsModuleError = CreateIeltsModuleErrors[keyof CreateIeltsModuleErrors];

export type CreateIeltsModuleResponses = {
    /**
     * Successful Response
     */
    200: ModuleRead;
};

export type CreateIeltsModuleResponse = CreateIeltsModuleResponses[keyof CreateIeltsModuleResponses];

export type AddFilesToIeltsModuleData = {
    body: BodyAddFilesToIeltsModule;
    path: {
        /**
         * Module Id
         */
        module_id: string;
    };
    query?: never;
    url: '/api/v1/ielts/modules/{module_id}/files';
};

export type AddFilesToIeltsModuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddFilesToIeltsModuleError = AddFilesToIeltsModuleErrors[keyof AddFilesToIeltsModuleErrors];

export type AddFilesToIeltsModuleResponses = {
    /**
     * Successful Response
     */
    200: ModuleRead;
};

export type AddFilesToIeltsModuleResponse = AddFilesToIeltsModuleResponses[keyof AddFilesToIeltsModuleResponses];

export type ReadIeltsModuleByIdData = {
    body?: never;
    path: {
        /**
         * Module Id
         */
        module_id: string;
    };
    query?: never;
    url: '/api/v1/ielts/modules/{module_id}';
};

export type ReadIeltsModuleByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadIeltsModuleByIdError = ReadIeltsModuleByIdErrors[keyof ReadIeltsModuleByIdErrors];

export type ReadIeltsModuleByIdResponses = {
    /**
     * Successful Response
     */
    200: ModuleRead;
};

export type ReadIeltsModuleByIdResponse = ReadIeltsModuleByIdResponses[keyof ReadIeltsModuleByIdResponses];

export type CreateIeltsAttemptData = {
    body: AttemptCreate;
    path?: never;
    query?: never;
    url: '/api/v1/ielts/attempts';
};

export type CreateIeltsAttemptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateIeltsAttemptError = CreateIeltsAttemptErrors[keyof CreateIeltsAttemptErrors];

export type CreateIeltsAttemptResponses = {
    /**
     * Successful Response
     */
    200: AttemptRead;
};

export type CreateIeltsAttemptResponse = CreateIeltsAttemptResponses[keyof CreateIeltsAttemptResponses];

export type ReadMyIeltsAttemptsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ielts/attempts/me';
};

export type ReadMyIeltsAttemptsResponses = {
    /**
     * Response Read My Ielts Attempts
     *
     * Successful Response
     */
    200: Array<AttemptRead>;
};

export type ReadMyIeltsAttemptsResponse = ReadMyIeltsAttemptsResponses[keyof ReadMyIeltsAttemptsResponses];
